# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\".\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\" \n\x12\x43reateUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x0fGetUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x12\x44\x65leteUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\":\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\";\n\x12UpdateUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x32\x9d\x02\n\x08UsersAPI\x12\x45\n\nCreateUser\x12\x1a.example.CreateUserRequest\x1a\x1b.example.CreateUserResponse\x12<\n\x07GetUser\x12\x17.example.GetUserRequest\x1a\x18.example.GetUserResponse\x12\x45\n\nDeleteUser\x12\x1a.example.DeleteUserRequest\x1a\x1b.example.DeleteUserResponse\x12\x45\n\nUpdateUser\x12\x1a.example.UpdateUserRequest\x1a\x1b.example.UpdateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=26
  _globals['_CREATEUSERREQUEST']._serialized_end=72
  _globals['_CREATEUSERRESPONSE']._serialized_start=74
  _globals['_CREATEUSERRESPONSE']._serialized_end=106
  _globals['_GETUSERREQUEST']._serialized_start=108
  _globals['_GETUSERREQUEST']._serialized_end=136
  _globals['_GETUSERRESPONSE']._serialized_start=138
  _globals['_GETUSERRESPONSE']._serialized_end=194
  _globals['_DELETEUSERREQUEST']._serialized_start=196
  _globals['_DELETEUSERREQUEST']._serialized_end=227
  _globals['_DELETEUSERRESPONSE']._serialized_start=229
  _globals['_DELETEUSERRESPONSE']._serialized_end=261
  _globals['_UPDATEUSERREQUEST']._serialized_start=263
  _globals['_UPDATEUSERREQUEST']._serialized_end=321
  _globals['_UPDATEUSERRESPONSE']._serialized_start=323
  _globals['_UPDATEUSERRESPONSE']._serialized_end=382
  _globals['_USERSAPI']._serialized_start=385
  _globals['_USERSAPI']._serialized_end=670
# @@protoc_insertion_point(module_scope)
